a=5
b=3
print("a+b =",(a+b))   #使用"+"运算
print("a-b =",(a-b))   #使用"-"运算
print("a*b =",(a*b))   #使用"*"运算
print("a/b =",(a/b))   #使用"/"运算
print("a%b =",(a%b))   #使用"%"运算
print("a//b =",(a//b))   #使用"//"运算
print("a**b =",(a**b))   #使用"**"运算
