# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'code9-14.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 10, 350, 200))
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)#設定列表中可多選
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)#設定選中方式為整行選中
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)#設定以清單形式顯示資料
        self.listWidget.setWordWrap(True)#設定自動換行
        from collections import OrderedDict

        dict=OrderedDict({'第一名':'戰狼2,2017年上映，票房56.83億','第2名':'哪吒之魔童降世，2019年上映，票房50.12億','第3名':'流浪地球，2019年上映，票房46.86億','第4名':'復仇者聯盟:終局之戰，2019年上映，票房42.50億',
                          '第5名':'紅海行動，2018年上映，票房36.51億','第6名':'唐人街探索2，2018年上映，票房33.98億','第7名':'美人魚，2016年上映，票房33.86億','第8名':'我和我的祖國，2019年上映，票房31.71億',
                          '第9名':'我不是藥神，2018年上映，票房31.00億','第10名':'中國機長，2019年上映，票房29.13億'})
        for key,value in dict.items():
            self.item=QtWidgets.QListWidgetItem(self.listWidget)
            self.item.setText(key+':'+value)
            self.item.setToolTip(value)
        self.listWidget.itemClicked.connect(self.gettext)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 269, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def gettext(self,item):
        if item.isSelected():
            from PyQt5.QtWidgets import QMessageBox
            QMessageBox.information(MainWindow,"提示","您選擇的是:"+item.text(),QMessageBox.Ok)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import sys
# 主方法，程序从此处启动PyQt设计的窗体
if __name__ == '__main__':
   app = QtWidgets.QApplication(sys.argv)
   MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
   ui = Ui_MainWindow() # 创建PyQt设计的窗体对象
   ui.setupUi(MainWindow) # 调用PyQt窗体的方法对窗体对象进行初始化设置
   MainWindow.show() # 显示窗体
   sys.exit(app.exec_()) # 程序关闭时退出进程